### ISSUE TITLE
Marks for hometask "Unit Testing"

### ISSUE THREAD

**Issue by rimus** [GarinaKristina/Stage_2#1]
1) Leave main branch empty.
2) Make hometask into separate branch (e.g. calculator).
3) After hometask solving you must open pull request and share the link with me.

**Comment by GarinaKristina** [comment]
Hi!
1.I deleted all bad files from main branch.
2.I created new files.
3.I did new open pul request .


Please.Don't look at my deleted files. I had not created ssh keys for git. I have to do this first of all.

Thanks for help.
